
export const CREATE_TASK = "CREATE_TASK";
export const RETRIEVE_TASK = "RETRIEVE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const RETRIEVE_STATUS_TASK = "RETRIEVE_STATUS_TASK";
export const RETRIEVE_USERGROUP_TASK = "RETRIEVE_USERGROUP_TASK";
export const RETRIEVE_COMPLETE_TASK = "RETRIEVE_COMPLETE_TASK";
export const MOVE_USER_TASK = "MOVE_USER_TASK";



export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RETRIEVE_ALL_USER = "RETRIEVE_ALL_USER";
export const GET_ALL_MOVE_USERS = "GET_ALL_MOVE_USERS";
export const RETRIEVE_USER_BY_ID = "RETRIEVE_USER_BY_ID";
export const BLOCK_USER = "BLOCK_USER";
export const UNBLOCK_USER = "UNBLOCK_USER";
export const EDIT_USER = "EDIT_USER";
export const DELETE_USER = "DELETE_USER";

export const RETRIEVE_USER_GROUP = "RETRIEVE_USER_GROUP";
export const CREATE_USER_GROUP = "CREATE_USER_GROUP";

